packages:
  - '.'

overrides:
  '@mastra/core': link:../../../../packages/core
  '@mastra/editor': link:../../../../packages/editor
  '@mastra/memory': link:../../../../packages/memory
  '@mastra/libsql': link:../../../../stores/libsql
  '@mastra/mcp': link:../../../../packages/mcp
  mastra: link:../../../../packages/cli
  '@mastra/react': link:../../../playground-ui
  '@mastra/loggers': link:../../../../packages/loggers
  '@mastra/pg': link:../../../../stores/pg
  '@mastra/rag': link:../../../../packages/rag
  '@mastra/ttsd': link:../../../../packages/ttsd
  '@internal/test-utils': link:../../../../packages/_test-utils

allowBuilds:
  esbuild: true
